SYSTEM_UTILS=(
        bat
        fd
        ffmpeg
        figlet
        font-symbols-only-nerd-font
        fzf
        gh
        imagemagick
        poppler
        resvg
        ripgrep
        sevenzip
        stow
        tldr
        tree
        wget
        zoxide
)

DEV_TOOLS=(
        git
        jq
        lazygit
        neovim
        yazi
        zellij
)


PROGRAMMING=(
        go
        node
        openjdk
)

MEDIA=(
        chafa
        mpv
)

OTHERS=(
        tree-sitter
        tree-sitter-cli
)
