SYSTEM_UTILS=(
        bat
        figlet
        fzf
        gh
        git
        ripgrep
        stow
        tree
        zoxide
        zsh
)

DEV_TOOLS=(
        lazygit
        neovim
        zellij
        yazi
)


PROGRAMMING=(
        go
        node
)

MEDIA=(
        chafa
        mpv
)

OTHERS=(
        tree-sitter
        tree-sitter-cli
)
